fail_fast: true
repos:
  - repo: local
    hooks:
      - id: system
        name: Black
        entry: poetry run black .
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: system
        name: isort
        entry: poetry run isort .
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: system
        name: MyPy
        # this is a general problem with Manim, it's type hints are completely fucked, thus all files using Manim dircectly have to be excluded
        entry: poetry run mypy . --exclude 'manim_editor/editor/assets.py|example.py'
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: system
        name: Codespell
        entry: poetry run codespell . --skip='./node_modules,./.mypy_cache,./docs/build,./.git,./media,./manim_editor/app/static/webpack' --ignore-words-list 'tread'
        pass_filenames: false
        language: system
  # - repo: local
  #   hooks:
  #     - id: system
  #       name: Flake8
  #       entry: poetry run 
  #       pass_filenames: false
  #       language: system
