[tool.poetry]
name = "manim_editor"
version = "0.1.0"
description = "Editor and Presenter for Manim Generated Content"
authors = ["christopher-besch <christopher.besch@gmx.de>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
Flask = "^2.0.2"
manim = { git = "https://github.com/ManimCommunity/manim", branch = "main" }
click = "^8.0.3"
waitress = "^2.0.0"
python-dotenv = "^0.19.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins]
[tool.poetry.plugins."console_scripts"]
"manedit" = "manim_editor.__main__:main"
